### ISSUE TITLE
OEM user language not save after installation

### ISSUE THREAD

**Issue by guinux** [philmmanjaro/project-sx#10]
At installation Calamares correctly find language from live system.
After reboot, at OEM configuration, Calamares language variable is set to English.

**Comment by oberon-manjaro** [comment]
I think this is fine, since the OEM session is the first thing the end user launches and it makes sense that they would configure the language they need, which may well be different from what the manufacturer wants when pre-installing the OS during first step.

**Comment by guinux** [comment]
Yes that makes sense, I just wondered why the pre-selected language is not the one used by the manufacturer when pre-installing.

**Comment by hphilm** [comment]
The user should select the language. Setting the language for the OEM installer is an option and helps him to understand the installer better. It never sets the locale for the user, though. It is working as designed.
