### ISSUE TITLE
tlpui update needed

### ISSUE THREAD

**Issue by oberon-manjaro** [philmmanjaro/project-sx#11]
Since gksu has been dropped I have attempted to update **tlpui**.
Apparently the repo has been redesigned, using setuptools now.
However unfortunately I was not able to get the application working ...
@philmmanjaro please have a look, thank! :smiley: 
https://github.com/philmmanjaro/project-sx/blob/master/packages/tlpui/PKGBUILD

**Comment by hphilm** [comment]
We always used **polkit** for it. Never used gksu? Did I miss some?

**Comment by hphilm** [comment]
OK, my bad. We used **gksu** for it in the past.

**Comment by hphilm** [comment]
https://github.com/philmmanjaro/project-sx/commit/6d2459fd6cc06a8ff3442f7a25d9118b4a4ab62e

**Comment by hphilm** [comment]
https://github.com/philmmanjaro/project-sx/commit/7834cf13cfc93a7048398ab360b87b0b6fc65434

**Comment by oberon-manjaro** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/tlp_ui", line 11, in <module>
    load_entry_point('TLPUI==0.1', 'gui_scripts', 'tlpui')()
  File "/usr/lib/python3.6/site-packages/tlpui/__main__.py", line 31, in main
    window.add(create_main_box(window))
  File "/usr/lib/python3.6/site-packages/tlpui/mainui.py", line 261, in create_main_box
    configbox = create_config_box(window)
  File "/usr/lib/python3.6/site-packages/tlpui/configui.py", line 25, in create_config_box
    tlp_categories = get_tlp_categories(window, categories)
  File "/usr/lib/python3.6/site-packages/tlpui/configui.py", line 230, in get_tlp_categories
    configbox = create_item_box(configobjects, description, grouptitle, window)
  File "/usr/lib/python3.6/site-packages/tlpui/configui.py", line 120, in create_item_box
    tlpobject = settings.tlpconfig[configname]
KeyError: 'USB_BLACKLIST_PRINTER'
```
The issue doesn't seem to be related to polkit ... 
What is it about `KeyError` ?

**Comment by d4nj1** [comment]
Hi.
USB_BLACKLIST_PRINTER was introduced in TLP 1.1 (https://github.com/linrunner/TLP/releases/tag/1.1)
Maybe your tlp config file in /etc/default/tlp is not up to date. Could you please check this and add USB_BLACKLIST_PRINTER to it?

If this is not the problem, please open a bug request at https://github.com/d4nj1/TLPUI with your TLP version and the TLPUI version you use.

**Comment by oberon-manjaro** [comment]
Thanks a lot! I had to merge the recent config, now it works as expected! :+1:

**Comment by hphilm** [comment]
@d4nj1: thx for your feedback. It is always good to have direct contact with the author :+1:
