### ISSUE TITLE
issue with comiling rtl8188eu module

### ISSUE THREAD

**Issue by hphilm** [philmmanjaro/project-sx#3]
We got following error:

```
/var/lib/dkms/rtl8188eu/r461.00b5f0d/build/os_dep/os_intfs.c: In function 'rtw_init_netdev':
/var/lib/dkms/rtl8188eu/r461.00b5f0d/build/os_dep/os_intfs.c:747:11: error: 'struct net_device' has no member named 'wireless_handlers'; did you mean 'rx_handler'?
  pnetdev->wireless_handlers = (struct iw_handler_def *)&rtw_handlers_def;
           ^~~~~~~~~~~~~~~~~
           rx_handler
make[1]: *** [scripts/Makefile.build:302: /var/lib/dkms/rtl8188eu/r461.00b5f0d/build/os_dep/os_intfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by hphilm** [comment]
Seems to be a config issue. `CONFIG_WIRELESS_EXT` needs to be enabled. Question is: do we need that driver anyway?

**Comment by oberon-manjaro** [comment]
**inxi** lists `Card-1: Realtek RTL8111/8168/8411`
I can check in the afternoon if it might work without the extramodule, but I doubt it...

**Comment by hphilm** [comment]
@oberon2007: this is a different chip-set. However if still needed we can modify the kernel `config` as needed. That is why I needed to know if all hardware got detected properly. When I got my machine I can check also. Currently it is just guessing.

**Comment by lisamccoy** [comment]
Well we don't need it anyway. Closing this issue.
