### ISSUE TITLE
Include 'laptop-mode-tools'

### ISSUE THREAD

**Issue by hphilm** [philmmanjaro/project-sx#4]
To enhance the battery life of **SX-SF** we should include **laptop-mode-tools** by default and configure it properly. **TC** uses it also. Didn't found it configured on **S76** machines yet. 

Arch has a [wiki entry](https://wiki.archlinux.org/index.php/Laptop_Mode_Tools) on it on how to configure. We might also check with the git-repo of **TC** to see how they use it, as we use the same chassis for **SX-SF**. 

@oberon2007: I reconstructed our repo so we have a working profile folder now.

**Comment by Chrysostomus** [comment]
In my experience tlp is better than laptop-mode-tools for power saving. Not sure if having a rotating disk would change that in the latters favor.

**Comment by lisamccoy** [comment]
yes, we are checking it now. there is a nice UI for tlp.
