### ISSUE TITLE
[calamares-oem] check oem user settings

### ISSUE THREAD

**Issue by hphilm** [philmmanjaro/project-sx#5]
@oberon2007: I managed now to get step two of **CAL OEM** going, however the QT5 style is not configured correctly within **oemskel**. Also take another look and optimize it if possible. I hope I did a great first draft of it. [Revision 2](https://sourceforge.net/projects/manjaro-sx/files/17.1-dev-170812/) of today's build is online now and includes those current changes.

No pressure with finding a solution. Eddie and his crew might be already wowed with its current state :smile_cat:

**Comment by oberon-manjaro** [comment]
fixed with https://github.com/philmmanjaro/project-sx/commit/89ec874319ec556f02596400e81ce702363c5905

**Comment by oberon-manjaro** [comment]
GREAT job with the OEM module btw! 😆 🚀
